spring:
  datasource:
    url: jdbc:mysql://localhost:3307/quart_test?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      max-lifetime: 1500000
      connection-timeout: 30000